name: Run Cypress Tests

on:
  schedule:
    - cron: '36 14 * * 1-5'  # Runs at 2:36 PM UTC, which is 8:06 PM IST on weekdays

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Run Cypress tests
      run: npx cypress run --spec cypress/e2e/spec/GreytHRLogin.cy.js --browser chrome
