name: Run Cypress Tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 4 * * 1-5'   # Runs at 4:00 AM UTC (9:30 AM IST) on weekdays
    - cron: '30 13 * * 1-5' # Runs at 1:30 PM UTC (7:00 PM IST) on weekdays

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run --spec cypress/e2e/spec/GreytHRLogin.cy.js --browser chrome
